### ISSUE TITLE
Expose Interface to other apps

### ISSUE THREAD

**Issue by LoggeL** [angturil/SongRequestManager#23]
Regarding #14 and #20 it would be pretty nice if you could expose a way to invoke a song request manually (e.g. WebSocket or HTTP-Request). This would allow the easy implementation of other sources instead of only limiting it to Twitch.

**Comment by Interpause** [comment]
Have you experimented with trying to write directly to songrequestqueue.dat? I don't know if it works yet but if it does that would be a cool workaround for now.

**Comment by endyb66** [comment]
@LoggeL It's some time ago since your post, were you able to find a way?

**Comment by LoggeL** [comment]
> 
> 
> @LoggeL It's some time ago since your post, were you able to find a way?

Sorry my knowledge regarding C# is quite limited and I didn't get any time to work on it.
