### ISSUE TITLE
[Request] Make the message when removing a song also configurable

### ISSUE THREAD

**Issue by Dragonissa** [angturil/SongRequestManager#76]
Currently it isn't possible to disable or change the message that gets shown when someone removes a song.
It is only possible for adding a song, which still leaves trolls the opportunity to use !wrongsong or !oops to remove the song and displaying the song name.

https://github.com/angturil/SongRequestManager/blob/46d40953b51488a2b316c82a10528cb401b6c664/EnhancedTwitchIntegration/Bot/ChatCommands.cs#L430=

**Comment by Krayn** [comment]
if you actually enable the censor it wont show the name.
![image](https://user-images.githubusercontent.com/3692964/178572587-b5fd8a7d-ff83-4ce9-8e83-1a1ef3bd1faf.png)


please verify you are using 2.15.10

**Comment by Dragonissa** [comment]
The censor is only time based, there can always be a song that slips through and is older than the default 10 minutes or whatever someone has configured in that moment.

Or is there a different censoring i'm not aware of?

**Comment by Krayn** [comment]
set the censoring to -10 so it censors independent of time

(i just uploaded v2.15.11 since i actually found (after verifying that i already censored the !oops/!wrongsong message) a double definition of a chat message that still made the artists name slip through)

**Comment by Dragonissa** [comment]
> set the censoring to -10 so it censors independent of time
> 
> (i just uploaded v2.15.11 since i actually found (after verifying that i already censored the !oops/!wrongsong message) a double definition of a chat message that still made the artists name slip through)

Ah alright, guess i misread the code. Thanks a lot for clarifying.
